### ISSUE TITLE
AWSQS::Kubernetes::Helm failing

### ISSUE THREAD

**Issue by wdtracy** [aws-quickstart/quickstart-eks-gitlab#116] opened 2022-04-14 20:21 UTC
Getting this error when trying to deploy quickstart into new VPC:

Resource handler returned message: "[errorString] Error: At Helm install - template: gitlab/templates/NOTES.txt:124:3:
executing "gitlab/templates/NOTES.txt" at <include "gitlab.deprecations" .>: error calling include: template:
gitlab/templates/_deprecations.tpl:64:46: executing "gitlab.deprecations" at <fail>: error calling fail: DEPRECATIONS:
gitlab.task-runner: The configuration of `gitlab.task-runner` has been renamed. Please use `gitlab.toolbox` instead. If
you have enabled persistence for `task-runner` and/or its CronJob for backups, you may need to manually bind the new
`toolbox` PVC to the previous `task-runner` PV. "

**Comment by kolomied** [comment] 2022-06-13 12:54
Thank you for reporting this and sorry for the long delay.
The issue is addressed in PR #111 - we are running deployment tests on our side to verify the changes. 
I'll update this issue once the PR is merged.

**Comment by kolomied** [comment] 2022-06-14 14:06
The PR was merged and helm chart configuration changes are incorporated.

**Comment by kolomied** [comment] 2022-09-30 14:00
Addressed in #111 - closing the issue

**Closed by kolomied** 2022-09-30 14:00 UTC
