### ISSUE TITLE
GitLabStack : KubeSecrets Failing

### ISSUE THREAD

**Issue by jonchines** [aws-quickstart/quickstart-eks-gitlab#105] opened 2021-11-16 17:26 UTC
Output 'SmtpCredentialsSecretName' not found in stack 'arn:aws:cloudformation:us-east-2:201113909371:stack/GitLab-EKS-QuickStart-GitLabStack-1IAPHD4VJQYF4-Infrastructure-UYRLR1I5P57N/7210b310-46fd-11ec-9f8f-0234feb05ba4'

I can see in GitLabStack : Infrastructure where the SES resoucres are made and the apparent call to Secrets Manager but this step completes successfully with only:

<html><body>

/quickstart/gitlab/Ironbank/secrets/gitlab-db-password | GitLab DB Password | 11/16/2021
-- | -- | --
/quickstart/gitlab/Ironbank/storage/credentials | GitLab Object Storage access keys

</body>
</html>

are actually written thus the Output for 'SmtpCredentialsSecretName' isn't being passed.

**Comment by jonchines** [comment] 2021-11-16 17:30
Additionally, GitLabStack : Infrastructure : Outputs show only:

<html><body>
<span><span>

DatabaseSecretName | arn:aws:secretsmanager:REGION:ACCOUNT:secret:/quickstart/gitlab/Ironbank/secrets/gitlab-db-password-fgjsOE | - | -
-- | -- | -- | --
DatabaseSecurityGroupID | sg-NUMBER | - | -
PraefectSecurityGroupID | sg-NUMBER | - | -
PrivateHostedZoneId | ZONEID | - | -

</span></span>
</body>
</html>

**Comment by gfysaris** [comment] 2022-04-20 09:44
Hello @jonchines ,
I am facing the same issue on our deployment.
Did you manage to find a workaround for this issue?

Regards

**Comment by kolomied** [comment] 2022-06-14 15:00
@jonchines, @gfysaris - thanks for reporting an issue and sorry for the delay.

Believe the problem is that you used the following combination of CFN parameters:

 - `CreateHostedZone`: **No** (default)
 - `SMTPDomain`: **CreateNew**

I've adjusted the implementation in the linked PR to ensure that SMTP domain can be created regardless of Route53 hosted zone. You can manage DNS outside of Route53 - this should not prevent you from creating an SMTP domain.

**Comment by kolomied** [comment] 2022-09-30 14:01
Addressed in #119 - closing the issue.

**Closed by kolomied** 2022-09-30 14:01 UTC
